### ISSUE TITLE
query_async is not drop safe

### ISSUE THREAD

**Issue by bikeshedder** [mitsuhiko/redis-rs#489] opened 2021-05-20 21:33 UTC
Given the following code...
```rust
cmd("PING")
      .arg("wrong")
      .query_async::<_, String>(&mut conn)
      .now_or_never();

let value: String = cmd("PING")
    .arg("right")
    .query_async(&mut conn)
    .await
    .unwrap();

assert_eq!(value, "right");
```

...the assertion fails because the first `query_async` is executed but the result is not retrieved. The second `query_async` call now receives the `"wrong"` PING response and all querys after that receive the response from one query earlier.

This issue was found by someone wondering why recycled connections from `deadpool-redis` were receiving the `PONG` from the connection recycling check: https://github.com/bikeshedder/deadpool/issues/97

This is not limited to pooled connections but could actually happen even when wrapping a `query_async` in a `tokio::time::timeout` or when using it as part of a `hyper` or `actix` service which don't poll futures to completion if the client goes away.

**Comment by Marwes** [comment] 2021-05-21 14:50
Closing as it is a duplicate of #325 (which has more discussion).

**Closed by Marwes** 2021-05-21 14:50 UTC
