### ISSUE TITLE
Show raw payload from Redis for passing through / Websockets / debugging?

### ISSUE THREAD

**Issue by theronic** [mitsuhiko/redis-rs#215] opened 2019-06-11 09:26 UTC
How can I access the raw payload that came back from Redis? I'm using redis-rs to deliver results from Redis via Websockets, but I'm having a hard time with FromRedisValue complaining that raw/bulk values cannot be cast to String or InfoDict.

Basically, I'm doing this, which always goes to the error branch of match because most things don't seems to be castable to String:

```
fn redis_handler(req: HttpRequest<AppState>) -> Result<HttpResponse, error::Error> {
    let tail: std::path::PathBuf = req.match_info().query("tail")?;
    let html = format!(r#"Redis result goes here: {:?}"#, tail); // whitelist commands?

    let client = redis::Client::open("redis://127.0.0.1/").unwrap();
    let conn = client.get_connection().unwrap();

    let mut cmd = redis::Cmd::new();
    let tail_string: Vec<&str> = tail.to_str().unwrap().split("/").collect(); // e.g. "/redis/XLEN/my-stream is like "XLEN my-stream"

    cmd.arg(tail_string);

    let result: redis::RedisResult<redis::InfoDict> = cmd.query(&conn);

    match result {
        Ok(thing) => {
            println!("Redis: {:?}", thing);
            let output = format!("{:?}", thing);
            Ok(HttpResponse::Ok().body(output))
        },
        Err(err) => {
            eprintln!("Redis Error: {:?}", err);
            Ok(HttpResponse::Ok().body("error"))
        },
    }
}
```

Which for an XRANGE query goes to error branch:

```
Redis Error: Response was of incompatible type: "Response type not string compatible." (response was bulk(bulk(string-data('"1559552599076-0"'), bulk(string-data('"system-state"'), string-data('"NORMAL"'))), bulk(string-data('"1559552599076-1"'), bulk(string-data('"breaker-state"'), string-data('"CLOSED"')))))
```

Is there a more generic type than InfoDict? I don't care about safety or performance at this stage - I just want to get something dirty working for an internal project. I realise that I could implement a handler for each command I care about, but I'm trying to keep it generic.

Any help would be appreciated :)

**Comment by badboy** [comment] 2019-06-11 10:08
redis-rs makes the explicit choice to give you a [`redis::Value`](https://docs.rs/redis/0.10.0/redis/enum.Value.html) or to convert to your type of choosing using [`FromRedisValue`](https://docs.rs/redis/0.10.0/redis/trait.FromRedisValue.html). There's no single good "string representation" for any Redis value. What's the string representation of a list, an integer, an error/success message?

If you need that, pick your format and decode the `redis::Value` (either adhoc for when you need it or by implementing `FromRedisValue` for your custom type).

I hope that helps with what you want to do. Closing this ticket, as it's not a bug.

Addendum: [`redis::InfoDict`](https://docs.rs/redis/0.10.0/redis/struct.InfoDict.html) is a special type to decode what `INFO` returns, which itself is an adhoc format, due to (early) Redis protocol not supporting what was necessary to encode all info. It's not an escape hatch to parse just about everything.

**Closed by badboy** 2019-06-11 10:08 UTC
